# Intro to PandaPower for IDP Project Optimization

In [1]:
try:
    from pandapower.networks.power_system_test_cases import case30
    from pandapower.run import runpp, runopp
    from pandapower.timeseries.run_time_series import run_timeseries
except: 
    %pip install pandapower
    %pip install numba
    from pandapower.networks.power_system_test_cases import case30
    from pandapower.run import runpp, runopp
    from pandapower.timeseries.run_time_series import run_timeseries

from tools.limits import bus_vm_pu_limits, line_loading_limits
import profileloader as pl
import numpy as np

### Import IEEE Case 30:
Case 30 is stored in a variable, "net", which consists of several dataframes. 
You can conceptualize a dataframe as being like a spreadsheet: It has named rows and columns, and data is stored in individual cells for each row/column pair. 
By default, the IEEE 30 net has a dataframe for each of the following grid components
- bus (30)
- load (21)
- generator (5)
- shunt (2)
- ext_grid (1)
- line (34)
- transformer (7)
- cost (6)

Additional components, such as for storage, motors, etc. can also be added to the net

In [2]:
net = case30()
print(net)

This pandapower network includes the following parameter tables:
   - bus (30 elements)
   - load (20 elements)
   - gen (5 elements)
   - shunt (2 elements)
   - ext_grid (1 element)
   - line (41 elements)
   - poly_cost (6 elements)

In [3]:
net.poly_cost

,element,et,cp0_eur,cp1_eur_per_mw,cp2_eur_per_mw2,cq0_eur,cq1_eur_per_mvar,cq2_eur_per_mvar2
0,0,ext_grid,0.0,2.00,0.02000,0.0,0.0,0.0
1,0,gen,0.0,1.75,0.01750,0.0,0.0,0.0
2,1,gen,0.0,1.00,0.06250,0.0,0.0,0.0
3,2,gen,0.0,3.25,0.00834,0.0,0.0,0.0
4,3,gen,0.0,3.00,0.02500,0.0,0.0,0.0
5,4,gen,0.0,3.00,0.02500,0.0,0.0,0.0

In [4]:
net.load.iloc[0:5,]

,name,bus,p_mw,q_mvar,const_z_p_percent,const_z_q_percent,const_i_p_percent,const_i_q_percent,sn_mva,scaling,in_service,type,controllable
0,None,1,21.7,12.7,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
1,None,2,2.4,1.2,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
2,None,3,7.6,1.6,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
3,None,6,22.8,10.9,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
4,None,7,30.0,30.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False

Specific cells are adjustable based on external data

In [5]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service,max_loading_percent,geo
0,None,None,0,1,1.0,3.6450,10.9350,436.639076,0.0,0.555967,1.0,1,ol,True,100.0,None
1,None,None,0,2,1.0,9.1125,34.6275,291.092717,0.0,0.555967,1.0,1,ol,True,100.0,None
2,None,None,1,3,1.0,10.9350,30.9825,291.092717,0.0,0.277983,1.0,1,ol,True,100.0,None
3,None,None,2,3,1.0,1.8225,7.2900,0.000000,0.0,0.555967,1.0,1,ol,True,100.0,None
4,None,None,1,4,1.0,9.1125,36.4500,291.092717,0.0,0.555967,1.0,1,ol,True,100.0,None
5,None,None,1,5,1.0,10.9350,32.8050,291.092717,0.0,0.277983,1.0,1,ol,True,100.0,None
6,None,None,3,5,1.0,1.8225,7.2900,0.000000,0.0,0.384900,1.0,1,ol,True,100.0,None
7,None,None,4,6,1.0,9.1125,21.8700,145.546359,0.0,0.299367,1.0,1,ol,True,100.0,None
8,None,None,5,6,1.0,5.4675,14.5800,145.546359,0.0,0.555967,1.0,1,ol,True,100.0,None
9,None,None,5,7,1.0,1.8225,7.2900,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
10,None,None,5,8,1.0,0.0000,38.2725,0.000000,0.0,0.277983,1.0,1,ol,True,100.0,None
11,None,None,5,9,1.0,0.0000,102.0600,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
12,None,None,8,10,1.0,0.0000,38.2725,0.000000,0.0,0.277983,1.0,1,ol,True,100.0,None
13,None,None,8,9,1.0,0.0000,20.0475,0.000000,0.0,0.277983,1.0,1,ol,True,100.0,None
14,None,None,3,11,1.0,0.0000,47.3850,0.000000,0.0,0.277983,1.0,1,ol,True,100.0,None
15,None,None,11,12,1.0,0.0000,25.5150,0.000000,0.0,0.277983,1.0,1,ol,True,100.0,None
16,None,None,11,13,1.0,21.8700,47.3850,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
17,None,None,11,14,1.0,12.7575,23.6925,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
18,None,None,11,15,1.0,16.4025,36.4500,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
19,None,None,13,14,1.0,40.0950,36.4500,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
20,None,None,15,16,1.0,14.5800,34.6275,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
21,None,None,14,17,1.0,20.0475,40.0950,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
22,None,None,17,18,1.0,10.9350,23.6925,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
23,None,None,18,19,1.0,5.4675,12.7575,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
24,None,None,9,19,1.0,16.4025,38.2725,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
25,None,None,9,16,1.0,5.4675,14.5800,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
26,None,None,9,20,1.0,5.4675,12.7575,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
27,None,None,9,21,1.0,12.7575,27.3375,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
28,None,None,20,21,1.0,1.8225,3.6450,0.000000,0.0,0.136853,1.0,1,ol,True,100.0,None
29,None,None,14,22,1.0,18.2250,36.4500,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
30,None,None,21,23,1.0,21.8700,32.8050,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
31,None,None,22,23,1.0,23.6925,49.2075,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
32,None,None,23,24,1.0,34.6275,60.1425,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
33,None,None,24,25,1.0,45.5625,69.2550,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
34,None,None,24,26,1.0,20.0475,38.2725,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
35,None,None,27,26,1.0,0.0000,72.9000,0.000000,0.0,0.277983,1.0,1,ol,True,100.0,None
36,None,None,26,28,1.0,40.0950,76.5450,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
37,None,None,26,29,1.0,58.3200,109.3500,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
38,None,None,28,29,1.0,43.7400,82.0125,0.000000,0.0,0.068427,1.0,1,ol,True,100.0,None
39,None,None,7,27,1.0,10.9350,36.4500,291.092717,0.0,0.136853,1.0,1,ol,True,100.0,None
40,None,None,5,27,1.0,3.6450,10.9350,145.546359,0.0,0.136853,1.0,1,ol,True,100.0,None

In [6]:
# for example: set the power consumption of load #1 to 2x its starting value
print("Before: " + str(net.load.at[0,'p_mw']))
net.load.at[0,'p_mw'] = 2 * net.load.iloc[0].p_mw
print("After: " + str(net.load.at[0,'p_mw']))

# and: set line loading limit to 50%
print("Before: " + str(net.line.at[10,'max_loading_percent']))
net.line.at[10,'max_loading_percent'] = 0.5
print("After: " + str(net.line.at[10,'max_loading_percent']))

Before: 21.7
After: 43.4
Before: 100.0
After: 0.5

### Power flow analysis
Analysis can be run on net using the runpp function. This adds a new set of dataframes to the net, containing result data for each bus, load, generator, etc.

In [7]:
runpp(net)
net.res_bus[0:5]

      vm_pu  va_degree       p_mw     q_mvar
0  1.000000   0.000000 -47.846249   7.653593
1  1.000000  -1.112025 -17.570000 -26.597780
2  0.983135  -1.940142   2.400000   1.200000
3  0.980162  -2.302209   7.600000   1.600000
4  0.982396  -2.490312   0.000000  -0.183369

In [8]:
net.res_gen

    p_mw     q_mvar  va_degree  vm_pu
0  60.97  39.297780  -1.112025    1.0
1  21.59  39.554809  -3.932185    1.0
2  26.91  10.527570  -1.374166    1.0
3  19.20   7.938512  -2.121219    1.0
4  37.00  11.319832   0.951621    1.0

You can use the result dataframes to check if power flow data is within the defined limits for each object

In [9]:
# For example, buses:
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
Line #9: Result 111.8198% loading is greater than maximum of 100.0% loading
Line #10: Result 10.4801% loading is greater than maximum of 0.5% loading

For purposes of optimization, grid components such as generators and loads have a boolean property called "controllable". If a component's "controllable" property is true, that means that the component can be changed during the optimization algorithm, to find which values produce the optimal grid conditions. Values where "controllable" is false are those which must be kept fixed.  
By default, all sources are controllable, and all loads are not.

In [10]:
runopp(net)

Below, you can see that the controllable grids have had their p_mw values changed. Compare the generator results with the generator results from before:

In [11]:
net.res_gen

        p_mw     q_mvar  va_degree     vm_pu
0  53.623339  25.937628  -0.964218  1.001399
1  28.286298   7.339579  -1.613982  0.994606
2  44.732117  29.905295   1.609648  1.068951
3  24.099484   9.353275  -0.788258  1.034163
4  22.954928  44.698565  -0.772041  1.086644

In [12]:
# proof that bus max/min values are now accounted for
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
All line loading within limits

To demonstrate optimization working if we set one of the generators to a fixed, non-controllable value:

In [13]:
net.gen.at[0,'p_mw'] = 20
net.gen.at[0, 'controllable'] = False
net.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,in_service,slack_weight,type,controllable,max_p_mw,min_p_mw,id_q_capability_characteristic,reactive_capability_curve,curve_style
0,None,1,20.00,1.0,NaN,-20.0,60.0,1.0,False,True,0.0,None,False,80.0,0.0,<NA>,False,None
1,None,21,21.59,1.0,NaN,-15.0,62.5,1.0,False,True,0.0,None,True,50.0,0.0,<NA>,False,None
2,None,26,26.91,1.0,NaN,-15.0,48.7,1.0,False,True,0.0,None,True,55.0,0.0,<NA>,False,None
3,None,22,19.20,1.0,NaN,-10.0,40.0,1.0,False,True,0.0,None,True,30.0,0.0,<NA>,False,None
4,None,12,37.00,1.0,NaN,-15.0,44.7,1.0,False,True,0.0,None,True,40.0,0.0,<NA>,False,None

In [14]:
runpp(net)
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
Line #9: Result 111.7991% loading is greater than maximum of 100.0% loading
Line #10: Result 10.3021% loading is greater than maximum of 0.5% loading

In [15]:
runopp(net)
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
All line loading within limits

The resulting optimized components have changed based on this new constraint.

In [16]:
net.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,in_service,slack_weight,type,controllable,max_p_mw,min_p_mw,id_q_capability_characteristic,reactive_capability_curve,curve_style
0,None,1,20.00,1.0,NaN,-20.0,60.0,1.0,False,True,0.0,None,False,80.0,0.0,<NA>,False,None
1,None,21,21.59,1.0,NaN,-15.0,62.5,1.0,False,True,0.0,None,True,50.0,0.0,<NA>,False,None
2,None,26,26.91,1.0,NaN,-15.0,48.7,1.0,False,True,0.0,None,True,55.0,0.0,<NA>,False,None
3,None,22,19.20,1.0,NaN,-10.0,40.0,1.0,False,True,0.0,None,True,30.0,0.0,<NA>,False,None
4,None,12,37.00,1.0,NaN,-15.0,44.7,1.0,False,True,0.0,None,True,40.0,0.0,<NA>,False,None

In [17]:
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,43.957613,-15.443639,-43.532274,13.719657,4.253394e-01,-1.723982,0.199257,0.195200,0.199257,1.000000,0.000000,1.000000,-1.671171,35.839697
1,15.439068,0.626980,-15.318562,-2.148366,1.205059e-01,-1.521386,0.066082,0.066849,0.066849,1.000000,0.000000,0.989600,-1.651520,12.023875
2,4.735411,4.438552,-4.704210,-6.326144,3.120118e-02,-1.887592,0.027757,0.034127,0.034127,1.000000,-1.671171,0.987925,-1.948803,12.276717
3,12.918564,0.948366,-12.901430,-0.879833,1.713338e-02,0.068534,0.055979,0.055979,0.055979,0.989600,-1.651520,0.987925,-1.948803,10.068811
4,7.992213,3.980393,-7.947873,-5.775497,4.433989e-02,-1.795104,0.038184,0.042608,0.042608,1.000000,-1.671171,0.986135,-2.455228,7.663728
5,7.404652,6.598837,-7.337109,-8.360373,6.754272e-02,-1.761536,0.042417,0.048447,0.048447,1.000000,-1.671171,0.981918,-2.182860,17.427977
6,12.819385,11.649953,-12.788641,-11.526978,3.074379e-02,0.122975,0.074987,0.074987,0.074987,0.987925,-1.948803,0.981918,-2.182860,19.482121
7,7.947874,5.960265,-7.894028,-6.791879,5.384575e-02,-0.831615,0.043084,0.045712,0.045712,0.986135,-2.455228,0.974282,-2.831778,15.269422
8,14.980366,3.349811,-14.905972,-4.108121,7.439444e-02,-0.758310,0.066857,0.067870,0.067870,0.981918,-2.182860,0.974282,-2.831778,12.207580
9,21.134492,23.251489,-21.032093,-22.841891,1.023995e-01,0.409598,0.136853,0.136853,0.136853,0.981918,-2.182860,0.970314,-2.551415,99.999733
10,-0.280208,-0.152559,0.280208,0.152780,0.000000e+00,0.000222,0.001390,0.001390,0.001390,0.981918,-2.182860,0.982245,-2.147904,0.499879
11,-0.160119,-0.087176,0.160119,0.087369,0.000000e+00,0.000193,0.000794,0.000794,0.000794,0.981918,-2.182860,0.982416,-2.129603,0.580217
12,0.000000,-0.000000,0.000000,-0.000000,0.000000e+00,-0.000000,0.000000,0.000000,0.000000,0.982245,-2.147904,0.982245,-2.147904,0.000000
13,-0.280208,-0.152780,0.280208,0.152896,0.000000e+00,0.000116,0.001390,0.001390,0.001390,0.982245,-2.147904,0.982416,-2.129603,0.499879
14,-2.813743,-6.043975,2.813743,6.162379,4.440892e-16,0.118404,0.028860,0.028860,0.028860,0.987925,-1.948803,1.003859,-1.526146,10.382046
15,-28.788114,-25.549858,28.788114,27.608115,0.000000e+00,2.058257,0.163980,0.163980,0.163980,1.003859,-1.526146,1.040266,0.685700,58.989185
16,4.087751,2.465176,-4.060616,-2.406385,2.713436e-02,0.058791,0.020336,0.020336,0.020336,1.003859,-1.526146,0.992617,-1.967173,14.860012
17,3.551316,4.348383,-3.529421,-4.307721,2.189490e-02,0.040662,0.023918,0.023918,0.023918,1.003859,-1.526146,0.995752,-1.616300,17.477226
18,7.135303,5.073920,-7.066841,-4.921782,6.846215e-02,0.152138,0.037300,0.037300,0.037300,1.003859,-1.526146,0.987400,-2.087088,27.255492
19,-2.139383,0.806385,2.151055,-0.795774,1.167159e-02,0.010611,0.009851,0.009851,0.009851,0.992617,-1.967173,0.995752,-1.616300,14.395732
20,3.566841,3.121782,-3.548405,-3.077997,1.843596e-02,0.043785,0.020530,0.020530,0.020530,0.987400,-2.087088,0.978513,-2.340873,30.003226
21,9.081755,3.552116,-8.976255,-3.341116,1.054998e-01,0.211000,0.041883,0.041883,0.041883,0.995752,-1.616300,0.978005,-2.561959,61.208171
22,5.776256,2.441116,-5.751588,-2.387670,2.466771e-02,0.053447,0.027422,0.027422,0.027422,0.978005,-2.561959,0.971236,-2.926559,40.074564
23,-3.748412,-1.012331,3.753206,1.023518,4.794471e-03,0.011187,0.017097,0.017097,0.017097,0.971236,-2.926559,0.973126,-2.785905,12.492798
24,5.989712,1.808698,-5.953206,-1.723518,3.650578e-02,0.085180,0.027237,0.027237,0.027237,0.982416,-2.129603,0.973126,-2.785905,19.902589
25,5.463229,2.753025,-5.451595,-2.722003,1.163333e-02,0.031022,0.026632,0.026632,0.026632,0.982416,-2.129603,0.978513,-2.340873,19.459934
26,-9.616719,-3.356461,9.648967,3.431707,3.224827e-02,0.075246,0.044340,0.044340,0.044340,0.982416,-2.129603,0.987761,-1.791588,32.399819
27,-8.076549,-3.445528,8.132470,3.565359,5.592094e-02,0.119831,0.038225,0.038225,0.038225,0.982416,-2.129603,0.993481,-1.559991,27.931113
28,-27.148967,-14.631707,27.246454,14.826680,9.748692e-02,0.194974,0.133530,0.133530,0.133530,0.987761,-1.791588,0.993481,-1.559991,97.571547
29,-15.903388,-0.948620,16.159376,1.460596,2.559878e-01,0.511976,0.068425,0.068425,0.068425,0.995752,-1.616300,1.014102,0.134865,99.997611
30,-8.702265,4.113374,8.814908,-3.944409,1.126430e-01,0.168965,0.041435,0.041435,0.041435,0.993481,-1.559991,0.996755,-0.367992,60.553821
31,5.219681,4.016809,-5.164845,-3.902918,5.483622e-02,0.113891,0.027776,0.027776,0.027776,1.014102,0.134865,0.996755,-0.367992,40.592152
32,-12.350058,1.187068,12.644438,-0.675776,2.943802e-01,0.511292,0.053233,0.053233,0.053233,0.996755,-0.367992,1.017282,2.063086,77.796047
33,3.543871,2.366684,-3.500000,-2.300000,4.387107e-02,0.066684,0.017915,0.017915,0.017915,1.017282,2.063086,0.999760,1.637746,26.181777
34,-16.188303,-1.690908,16.469898,2.228499,2.815952e-01,0.537591,0.068426,0.068426,0.068426,1.017282,2.063086,1.038758,3.805768,99.999144
35,-24.650150,-11.167916,24.650150,14.164174,3.552714e-15,2.996258,0.117048,0.117048,0.117048,0.988782,-1.703030,1.038758,3.805768,42.106221
36,6.163819,1.664518,-6.080707,-1.505850,8.311192e-02,0.158668,0.026286,0.026286,0.026286,1.038758,3.805768,1.019198,2.602825,38.414955
37,7.109416,1.650635,-6.951440,-1.354430,1.579760e-01,0.296205,0.030049,0.030049,0.030049,1.038758,3.805768,1.007964,1.760122,43.913756
38,3.680707,0.605850,-3.648558,-0.545571,3.214896e-02,0.060279,0.015652,0.015652,0.015652,1.019198,2.602825,1.007964,1.760122,22.874828
39,-8.967907,-7.158108,9.043786,5.491842,7.587989e-02,-1.666266,0.050574,0.045763,0.050574,0.970314,-2.551415,0.988782,-1.703030,36.954522
40,-15.548779,-6.474213,15.606377,5.676081,5.759813e-02,-0.798132,0.073357,0.071826,0.073357,0.981918,-2.182860,0.988782,-1.703030,53.602979

In [18]:
#const_load = pl.csv_to_net(net, "load")

In [ ]:
load_control = pl.json_to_net(net, "load")
gen_conrol = pl.json_to_net(net, "gen")

In [21]:
print(net.gen)

   name  bus       p_mw  vm_pu  sn_mva  min_q_mvar  max_q_mvar  scaling  \
0  None    1  -1.069760    1.0     NaN       -20.0        60.0      1.0
1  None   21  -5.348801    1.0     NaN       -15.0        62.5      1.0
2  None   26   0.000000    1.0     NaN       -15.0        48.7      1.0
3  None   22   0.000000    1.0     NaN       -10.0        40.0      1.0
4  None   12 -10.697601    1.0     NaN       -15.0        44.7      1.0

   slack  in_service  slack_weight  type  controllable  max_p_mw  min_p_mw  \
0  False        True           0.0  None         False      80.0       0.0
1  False        True           0.0  None          True      50.0       0.0
2  False        True           0.0  None          True      55.0       0.0
3  False        True           0.0  None          True      30.0       0.0
4  False        True           0.0  None          True      40.0       0.0

   id_q_capability_characteristic  reactive_capability_curve curve_style
0                            <NA>                      False        None
1                            <NA>                      False        None
2                            <NA>                      False        None
3                            <NA>                      False        None
4                            <NA>                      False        None

In [20]:
run_timeseries(net)

No time steps to calculate are specified. I'll check the datasource of the first controller for avaiable time steps
  0%|          | 0/35401 [00:00<?, ?it/s]CalculationNotConverged at time step 0

LoadflowNotConverged: